version: "3"

services: 
    flask:
        build: ./flask2
        container_name: flask2
        restart: always
        environment: 
            - APP_NAME=FlaskTest
        expose:
            - 8081

    nginx:
        build: ./nginx2
        container_name: nginx2
        restart: always
        ports:
            - "5001:5001"

    updater:
        build: ./updater2
        container_name: updater2
